=== dglo/StringHub/src/main/resources/icecube/daq/configuration/domconfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="domConfigList" type="domConfigListType"/>
    
    <xs:simpleType name="dac10">
        <xs:annotation>
            <xs:documentation>
                Subclass of int to handle 10-bit signed integers
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxExclusive value="1024"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="dac12">
        <xs:annotation>
            <xs:documentation>
                Subclass of int to handle 12-bit signed integers
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxExclusive value="4096"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="AtwdChannel">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxExclusive value="4"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="DataFormatType">
        <xs:annotation>
            <xs:documentation>
                Sets the DOM data readout format.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:choice>
                <xs:element name="deltaCompressed">
                    <xs:annotation>
                        <xs:documentation>
                            Selects the delta compression codec.
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:attribute name="codec">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="1-2-3-6-11"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="engineeringFormat">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fadcSamples">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="255"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="atwd" minOccurs="4" maxOccurs="4">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="samples">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:int">
                                                    <xs:enumeration value="128"/>
                                                    <xs:enumeration value="64"/>
                                                    <xs:enumeration value="32"/>
                                                    <xs:enumeration value="16"/>
                                                    <xs:enumeration value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="width" minOccurs="0" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:int">
                                                    <xs:enumeration value="1"/>
                                                    <xs:enumeration value="2"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="ch" type="AtwdChannel" use="required"/>
                                    </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
            <xs:element name="pedestalSubtract" type="xs:boolean" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="TriggerWindowType">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="100"/>
            <xs:maxInclusive value="3200"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="CableLengthDelayType">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="3200"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="SpanType">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="4"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="LocalCoincidenceType">
        <xs:sequence>
            <xs:element name="type">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="soft"/>
                        <xs:enumeration value="hard"/>
                        <xs:enumeration value="flabby"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="mode">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="none"/>
                        <xs:enumeration value="up-or-down"/>
                        <xs:enumeration value="up"/>
                        <xs:enumeration value="down"/>
                        <xs:enumeration value="up-and-down"/>
                        <xs:enumeration value="headers-only"/>
                    </xs:restriction>
                    </xs:simpleType>
            </xs:element>
            <xs:element name="txMode">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="none"/>
                        <xs:enumeration value="both"/>
                        <xs:enumeration value="up"/>
                        <xs:enumeration value="down"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="source">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="spe"/>
                        <xs:enumeration value="mpe"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="span" type="SpanType"/>
            <xs:element name="preTrigger" type="TriggerWindowType"/>
            <xs:element name="postTrigger" type="TriggerWindowType"/>
            <xs:element name="cableLength" minOccurs="0" maxOccurs="8">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="CableLengthDelayType">
                            <xs:attribute name="dir">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="up"/>
                                        <xs:enumeration value="down"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:attribute>
                            <xs:attribute name="dist" type="SpanType"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>    
    </xs:complexType>
    
    <xs:complexType name="DomConfigType">
        <xs:all>
            <xs:element name="format" type="DataFormatType"/>
            <xs:element name="triggerMode">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="forced"/>
                        <xs:enumeration value="spe"/>
                        <xs:enumeration value="mpe"/>
                        <xs:enumeration value="flasher"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            
            <!-- The 16 mainboard DACs --> 
            <xs:element name="atwd0TriggerBias" type="dac12"/>
            <xs:element name="atwd0RampTop" type="dac12"/>
            <xs:element name="atwd0RampRate" type="dac12"/>
            <xs:element name="atwdAnalogRef" type="dac12"/>
            <xs:element name="atwd1TriggerBias" type="dac12"/>
            <xs:element name="atwd1RampTop" type="dac12"/>
            <xs:element name="atwd1RampRate" type="dac12"/>
            <xs:element name="frontEndPedestal" type="dac12"/>
            <xs:element name="mpeTriggerDiscriminator" type="dac10"/>
            <xs:element name="speTriggerDiscriminator" type="dac10"/>
            <xs:element name="fastAdcRef" type="dac10"/>
            <xs:element name="internalPulser" type="dac10"/>
            <xs:element name="ledBrightness" type="dac10"/>
            <xs:element name="frontEndAmpLowerClamp" type="dac10"/>
            <xs:element name="flasherDelay" type="dac10"/>
            <xs:element name="muxBias" type="dac10"/>
            
            <!-- The PMT HV DAC is actually on the HV digital interface PCB -->
            <xs:element name="pmtHighVoltage" type="dac12"/>
            
            <xs:element name="analogMux">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="off"/>
                        <xs:enumeration value="clock"/>
                        <xs:enumeration value="clock2x"/>
                        <xs:enumeration value="onboardLedCurrent"/>
                        <xs:enumeration value="flasherLedCurrent"/>
                        <xs:enumeration value="localCoincidenceDown"/>
                        <xs:enumeration value="localCoincidenceUp"/>
                        <xs:enumeration value="commAdc"/>
                        <xs:enumeration value="internalPulser"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            
            <xs:element name="pulserMode">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="beacon"/>
                        <xs:enumeration value="pulser"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            
            <xs:element name="pulserRate" type="xs:short"/>

            <xs:element name="localCoincidence" type="LocalCoincidenceType"/>
            
            <xs:element name="supernovaMode">
                <xs:complexType>
                    <xs:sequence>
                       <xs:element name="deadtime">
                           <xs:simpleType>
                               <xs:restriction base="xs:int">
                                   <xs:minInclusive value="6400"/>
                                   <xs:maxInclusive value="819200"/>
                               </xs:restriction>
                           </xs:simpleType>
                       </xs:element> 
                       <xs:element name="disc">
                           <xs:simpleType>
                               <xs:restriction base="xs:token">
                                   <xs:enumeration value="mpe"/>
                                   <xs:enumeration value="spe"/>
                               </xs:restriction>
                           </xs:simpleType>
                       </xs:element>
                    </xs:sequence>
                    <xs:attribute name="enabled" type="xs:boolean"/>
                </xs:complexType>
            </xs:element>
            
            <xs:element name="scalerDeadtime">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="100"/>
                        <xs:maxInclusive value="102400"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            
            <xs:element name="hardwareMonitorInterval" type="xs:unsignedInt" minOccurs="0"/>
            <xs:element name="configMonitorInterval" type="xs:unsignedInt" minOccurs="0"/>
            
        </xs:all>
            
        <xs:attribute name="mbid" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9a-f]{12}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="name" use="optional" type="xs:string"/>
    </xs:complexType>
    
    <xs:complexType name="domConfigListType">
        <xs:sequence>
            <xs:element name="creator" type="xs:string" minOccurs="0"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="domConfig" type="DomConfigType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="configId" type="xs:int" use="required"/>
    </xs:complexType>
</xs:schema>

=== dglo/StringHub/src/main/resources/icecube/daq/configuration/sample-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<domConfigList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="domconfig.xsd" configId="10102030">

    <creator>Kael Hanson</creator>
    
    <description>
        A test config file to illustrate an example of a valid DOM.
    </description>

    <domConfig mbid="57bc3f3a220d">
        <format> 
            <engineeringFormat>
                <fadcSamples>200</fadcSamples>
                <atwd ch="0">
                    <samples >128</samples>
                </atwd>
                <atwd ch="1">
                    <samples>32</samples>
                </atwd>
                <atwd ch="2">
                    <samples>32</samples>
                </atwd>
                <atwd ch="3">
                    <samples>0</samples>
                </atwd>
            </engineeringFormat> 
        </format>
        <triggerMode>spe</triggerMode>
        <atwd0TriggerBias>828</atwd0TriggerBias>
        <atwd0RampTop>2100</atwd0RampTop>
        <atwd0RampRate>370</atwd0RampRate>
        <atwdAnalogRef>1750</atwdAnalogRef>
        <atwd1TriggerBias>843</atwd1TriggerBias>
        <atwd1RampTop>2300</atwd1RampTop>
        <atwd1RampRate>366</atwd1RampRate>
        <frontEndPedestal>1975</frontEndPedestal>
        <mpeTriggerDiscriminator>665</mpeTriggerDiscriminator>
        <speTriggerDiscriminator>569</speTriggerDiscriminator>
        <fastAdcRef>820</fastAdcRef>
        <internalPulser>30</internalPulser>
        <ledBrightness>1023</ledBrightness>
        <frontEndAmpLowerClamp>0</frontEndAmpLowerClamp>
        <flasherDelay>0</flasherDelay>
        <muxBias>0</muxBias>
        <pmtHighVoltage>2846</pmtHighVoltage>
        <analogMux>off</analogMux>
        <pulserMode>beacon</pulserMode>
        <pulserRate>58</pulserRate>
        <localCoincidence>
            <type>soft</type>
            <mode>up-or-down</mode>
            <txMode>both</txMode>
            <source>spe</source>
            <span>3</span>
            <preTrigger>1250</preTrigger>
            <postTrigger>1250</postTrigger>
            <cableLength dir="up" dist="1">650</cableLength>
            <cableLength dir="up" dist="2">1300</cableLength>
            <cableLength dir="down" dist="1">575</cableLength>
            <cableLength dir="down" dist="2">1150</cableLength>
        </localCoincidence>
        <supernovaMode>
            <deadtime>250000</deadtime>
            <disc>spe</disc>
        </supernovaMode>
        <scalerDeadtime>50000</scalerDeadtime>
    </domConfig>
</domConfigList>
